//
//  Pokemon.swift
//  Pokecoso3
//
//  Created by Fabbio on 20/05/2019.
//  Copyright © 2019 Fabbio. All rights reserved.
//

import Foundation

struct Pokemon {
    let nomePkmn : String
    let categoria : [String]
    let numero : Int
    let peso : String
}

 let listaPkmn = [
    Pokemon(nomePkmn: "Bulbasaur", categoria: [""], numero: 1, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Ivysaur", categoria: [""], numero: 2, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Venusaur", categoria: [""], numero: 3, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Charmander", categoria: [""], numero: 4, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Charmeleon", categoria: [""], numero: 5, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Charizard", categoria: [""], numero: 6, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Squirtle", categoria: [""], numero: 7, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Wartortle", categoria: [""], numero: 8, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Blastoise", categoria: [""], numero: 9, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Caterpie", categoria: [""], numero: 10, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Metapod", categoria: [""], numero: 11, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Butterfree", categoria: [""], numero: 12, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Weedle", categoria: [""], numero: 13, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Kakuna", categoria: [""], numero: 14, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Beedrill", categoria: [""], numero: 15, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Pidgey", categoria: [""], numero: 16, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Pidgeotto", categoria: [""], numero: 17, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Pidgeot", categoria: [""], numero: 18, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Rattata", categoria: [""], numero: 19, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Raticate", categoria: [""], numero: 20, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Spearow", categoria: [""], numero: 21, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Fearow", categoria: [""], numero: 22, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Ekans", categoria: [""], numero: 23, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Arbok", categoria: [""], numero: 24, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Pikachu", categoria: [""], numero: 25, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Raichu", categoria: [""], numero: 26, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Sandshrew", categoria: [""], numero: 27, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Sandslash", categoria: [""], numero: 28, peso: "6,9 kg"),
    Pokemon(nomePkmn: "NidoranF", categoria: [""], numero: 29, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Nidorina", categoria: [""], numero: 30, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Nidoqueen", categoria: [""], numero: 31, peso: "6,9 kg"),
    Pokemon(nomePkmn: "NidoranM", categoria: [""], numero: 32, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Nidorino", categoria: [""], numero: 33, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Nidoking", categoria: [""], numero: 34, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Clefairy", categoria: [""], numero: 35, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Clefable", categoria: [""], numero: 36, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Vulpix", categoria: [""], numero: 37, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Ninetales", categoria: [""], numero: 38, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Jigglypuff", categoria: [""], numero: 39, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Wigglytuff", categoria: [""], numero: 40, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Zubat", categoria: [""], numero: 41, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Golbat", categoria: [""], numero: 42, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Oddish", categoria: [""], numero: 43, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Gloom", categoria: [""], numero: 44, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Vileplume", categoria: [""], numero: 45, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Paras", categoria: [""], numero: 46, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Parasect", categoria: [""], numero: 47, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Venonat", categoria: [""], numero: 48, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Venomoth", categoria: [""], numero: 49, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Diglett", categoria: [""], numero: 50, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Dugtrio", categoria: [""], numero: 51, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Meowth", categoria: [""], numero: 52, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Persian", categoria: [""], numero: 53, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Psyduck", categoria: [""], numero: 54, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Golduck", categoria: [""], numero: 55, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Monkey", categoria: [""], numero: 56, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Primeape", categoria: [""], numero: 57, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Growlithe", categoria: [""], numero: 58, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Arcanine", categoria: [""], numero: 59, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Poliwag", categoria: [""], numero: 60, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Poliwhirl", categoria: [""], numero: 61, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Poliwrath", categoria: [""], numero: 62, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Abra", categoria: [""], numero: 63, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Kadabra", categoria: [""], numero: 64, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Alakazam", categoria: [""], numero: 65, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Machop", categoria: [""], numero: 66, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Machoke", categoria: [""], numero: 67, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Machamp", categoria: [""], numero: 68, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Bellsprout", categoria: [""], numero: 69, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Weepinbell", categoria: [""], numero: 70, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Victreebel", categoria: [""], numero: 71, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Tentacool", categoria: [""], numero: 72, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Tentacruel", categoria: [""], numero: 73, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Geodude", categoria: [""], numero: 74, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Graveler", categoria: [""], numero: 75, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Golem", categoria: [""], numero: 76, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Ponyta", categoria: [""], numero: 77, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Rapidash", categoria: [""], numero: 78, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Slowpoke", categoria: [""], numero: 79, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Slowbro", categoria: [""], numero: 80, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Magnemite", categoria: [""], numero: 81, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Magneton", categoria: [""], numero: 82, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Farfetch'd", categoria: [""], numero: 83, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Doduo", categoria: [""], numero: 84, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Dodrio", categoria: [""], numero: 85, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Seel", categoria: [""], numero: 86, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Dewgong", categoria: [""], numero: 87, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Grimer", categoria: [""], numero: 88, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Muk", categoria: [""], numero: 89, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Shellder", categoria: [""], numero: 90, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Cloyster", categoria: [""], numero: 91, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Gastly", categoria: [""], numero: 92, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Hunter", categoria: [""], numero: 93, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Gengar", categoria: [""], numero: 94, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Onix", categoria: [""], numero: 95, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Drowzee", categoria: [""], numero: 96, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Hypno", categoria: [""], numero: 97, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Krabby", categoria: [""], numero: 98, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Kingler", categoria: [""], numero: 99, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Voltorb", categoria: [""], numero: 100, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Electrode", categoria: [""], numero: 101, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Exeggcute", categoria: [""], numero: 102, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Exeggutor", categoria: [""], numero: 103, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Cubone", categoria: [""], numero: 104, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Marowak", categoria: [""], numero: 105, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Hitmonlee", categoria: [""], numero: 106, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Hitmonchan", categoria: [""], numero: 107, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Lickitung", categoria: [""], numero: 108, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Koffing", categoria: [""], numero: 109, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Weezing", categoria: [""], numero: 110, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Rhyhorn", categoria: [""], numero: 111, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Rhydon", categoria: [""], numero: 112, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Chansey", categoria: [""], numero: 113, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Tangela", categoria: [""], numero: 114, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Kangaskhan", categoria: [""], numero: 115, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Horsea", categoria: [""], numero: 116, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Seadra", categoria: [""], numero: 117, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Goldeen", categoria: [""], numero: 118, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Seaking", categoria: [""], numero: 119, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Staryu", categoria: [""], numero: 120, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Starmie", categoria: [""], numero: 121, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Mr.Mime", categoria: [""], numero: 122, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Schyter", categoria: [""], numero: 123, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Jinx", categoria: [""], numero: 124, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Electabuzz", categoria: [""], numero: 125, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Magmar", categoria: [""], numero: 126, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Pinsir", categoria: [""], numero: 127, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Tauros", categoria: [""], numero: 128, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Magikarp", categoria: [""], numero: 129, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Gyarados", categoria: [""], numero: 130, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Lapras", categoria: [""], numero: 131, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Ditto", categoria: [""], numero: 132, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Eevee", categoria: [""], numero: 133, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Vaporeon", categoria: [""], numero: 134, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Jolteon", categoria: [""], numero: 135, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Flareon", categoria: [""], numero: 136, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Porygon", categoria: [""], numero: 137, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Omanyte", categoria: [""], numero: 138, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Omastar", categoria: [""], numero: 139, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Kabuto", categoria: [""], numero: 140, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Kabutops", categoria: [""], numero: 141, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Aerodactyl", categoria: [""], numero: 142, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Snorlax", categoria: [""], numero: 143, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Articuno", categoria: [""], numero: 144, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Zapdos", categoria: [""], numero: 145, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Moltres", categoria: [""], numero: 146, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Dratini", categoria: [""], numero: 147, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Dragonair", categoria: [""], numero: 148, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Dragonite", categoria: [""], numero: 149, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Mewtwo", categoria: [""], numero: 150, peso: "6,9 kg"),
    Pokemon(nomePkmn: "Mew", categoria: [""], numero: 151, peso: "6,9 kg")
]
