//
//  Pokemon.swift
//  Pokecoso3
//
//  Created by Fabbio on 20/05/2019.
//  Copyright © 2019 Fabbio. All rights reserved.
//

import Foundation

struct Pokemon {
    let nomePkmn : String
    let categoria : [String]
    let numero : Int
    let peso : String
    let altezza : String
}

 let listaPkmn = [
    Pokemon(nomePkmn: "Bulbasaur", categoria: ["Erba", "Veleno"], numero: 1, peso: "6,9 kg", altezza: "0,7 m"),
    Pokemon(nomePkmn: "Ivysaur", categoria: ["Erba", "Veleno"], numero: 2, peso: "13 kg", altezza: "1,0 m"),
    Pokemon(nomePkmn: "Venusaur", categoria: ["Erba", "Veleno"], numero: 3, peso: "100 kg", altezza: "2,0 m"),
    Pokemon(nomePkmn: "Charmander", categoria: ["Fuoco", ""], numero: 4, peso: "8,5 kg", altezza: "0,6 m"),
    Pokemon(nomePkmn: "Charmeleon", categoria: ["Fuoco", ""], numero: 5, peso: "19 kg", altezza: "1,1 m"),
    Pokemon(nomePkmn: "Charizard", categoria: ["Fuoco", "Volante"], numero: 6, peso: "90,5 kg", altezza: "1,7 m"),
    Pokemon(nomePkmn: "Squirtle", categoria: ["Acqua", ""], numero: 7, peso: "9,0 kg", altezza: "0,5 m"),
    Pokemon(nomePkmn: "Wartortle", categoria: ["Acqua", ""], numero: 8, peso: "22,5 kg", altezza: "1,0 m"),
    Pokemon(nomePkmn: "Blastoise", categoria: ["Acqua", ""], numero: 9, peso: "85,5 kg", altezza: "1,6 m"),
    Pokemon(nomePkmn: "Caterpie", categoria: ["Coleottero", ""], numero: 10, peso: "2,9 kg", altezza: "0,3 m"),
    Pokemon(nomePkmn: "Metapod", categoria: ["Coleottero", ""], numero: 11, peso: "9,9 kg", altezza: "0,7 m"),
    Pokemon(nomePkmn: "Butterfree", categoria: ["Coleottero", "Volante"], numero: 12, peso: "32,0 kg", altezza: "1,1 m"),
    Pokemon(nomePkmn: "Weedle", categoria: ["Coleottero", "Volante"], numero: 13, peso: "3,2 kg", altezza: "0,3 m"),
    Pokemon(nomePkmn: "Kakuna", categoria: ["Coleottero", "Volante"], numero: 14, peso: "10,0 kg", altezza: "0,6 m"),
    Pokemon(nomePkmn: "Beedrill", categoria: ["Coleottero", "Veleno"], numero: 15, peso: "29,5 kg", altezza: "1,0 m"),
    Pokemon(nomePkmn: "Pidgey", categoria: ["Normale", "Volante"], numero: 16, peso: "1,8 kg", altezza: "0,3 m"),
    Pokemon(nomePkmn: "Pidgeotto", categoria: ["Normale", "Volante"], numero: 17, peso: "30,0 kg", altezza: "1,1 m"),
    Pokemon(nomePkmn: "Pidgeot", categoria: ["Normale", "Volante"], numero: 18, peso: "39,5 kg", altezza: "1,5 m"),
    Pokemon(nomePkmn: "Rattata", categoria: ["Normale", ""], numero: 19, peso: "3,5 kg", altezza: "0,3 m"),
    Pokemon(nomePkmn: "Raticate", categoria: ["Normale", ""], numero: 20, peso: "18,5 kg", altezza: "0,7 m"),
    Pokemon(nomePkmn: "Spearow", categoria: ["Normale", "Volante"], numero: 21, peso: "2,0 kg", altezza: "0,3 m"),
    Pokemon(nomePkmn: "Fearow", categoria: ["Normale", "Volante"], numero: 22, peso: "38,0 kg", altezza: "1,2 m"),
    Pokemon(nomePkmn: "Ekans", categoria: ["Veleno", ""], numero: 23, peso: "6,9 kg", altezza: "2,0 m"),
    Pokemon(nomePkmn: "Arbok", categoria: ["Veleno", ""], numero: 24, peso: "65,0 kg", altezza: "3,5 m"),
    Pokemon(nomePkmn: "Pikachu", categoria: ["Elettro", ""], numero: 25, peso: "6,0 kg", altezza: "0,4 m"),
    Pokemon(nomePkmn: "Raichu", categoria: ["Elettro", ""], numero: 26, peso: "30,0 kg", altezza: "0,8 m"),
    Pokemon(nomePkmn: "Sandshrew", categoria: ["Terra", ""], numero: 27, peso: "12,0 kg", altezza: "0,6 m"),
    Pokemon(nomePkmn: "Sandslash", categoria: ["Terra", ""], numero: 28, peso: "29,5 kg", altezza: "1,0 m"),
    Pokemon(nomePkmn: "NidoranF", categoria: ["Veleno", ""], numero: 29, peso: "7,0 kg", altezza: "0,4 m"),
    Pokemon(nomePkmn: "Nidorina", categoria: ["Veleno", ""], numero: 30, peso: "20,0 kg", altezza: "0,8 m"),
    Pokemon(nomePkmn: "Nidoqueen", categoria: ["Veleno", "Terra"], numero: 31, peso: "60,0 kg", altezza: "1,3 m"),
    Pokemon(nomePkmn: "NidoranM", categoria: ["Veleno", ""], numero: 32, peso: "9,0 kg", altezza: "0,5 m"),
    Pokemon(nomePkmn: "Nidorino", categoria: ["Veleno", ""], numero: 33, peso: "19,5 kg", altezza: "0,9 m"),
    Pokemon(nomePkmn: "Nidoking", categoria: ["Veleno", "Terra"], numero: 34, peso: "62 kg", altezza: "1,4 m"),
    Pokemon(nomePkmn: "Clefairy", categoria: ["Folletto", ""], numero: 35, peso: "7,5 kg", altezza: "0,6 m"),
    Pokemon(nomePkmn: "Clefable", categoria: ["Folletto", ""], numero: 36, peso: "40,0 kg", altezza: "1,3 m"),
    Pokemon(nomePkmn: "Vulpix", categoria: ["Fuoco", ""], numero: 37, peso: "9,9 kg", altezza: "0,6 m"),
    Pokemon(nomePkmn: "Ninetales", categoria: ["Fuoco", ""], numero: 38, peso: "19,9 kg", altezza: "1,1 m"),
    Pokemon(nomePkmn: "Jigglypuff", categoria: ["Normale", "Folletto"], numero: 39, peso: "5,5 kg", altezza: "0,5 m"),
    Pokemon(nomePkmn: "Wigglytuff", categoria: ["Normale", "Folletto"], numero: 40, peso: "12,0 kg", altezza: "1,0 m"),
    Pokemon(nomePkmn: "Zubat", categoria: ["Veleno", "Volante"], numero: 41, peso: "7,5 kg", altezza: "0,8 m"),
    Pokemon(nomePkmn: "Golbat", categoria: ["Veleno", "Volante"], numero: 42, peso: "55,0 kg", altezza: "1,6 m"),
    Pokemon(nomePkmn: "Oddish", categoria: ["Erba", "Veleno"], numero: 43, peso: "5,4 kg", altezza: "0,5 m"),
    Pokemon(nomePkmn: "Gloom", categoria: ["Erba", "Veleno"], numero: 44, peso: "8,6 kg", altezza: "0,8 m"),
    Pokemon(nomePkmn: "Vileplume", categoria: ["Erba", "Veleno"], numero: 45, peso: "18,6 kg", altezza: "1,2 m"),
    Pokemon(nomePkmn: "Paras", categoria: ["Coleottero", "Erba"], numero: 46, peso: "5,4 kg", altezza: "0,3 m"),
    Pokemon(nomePkmn: "Parasect", categoria: ["Coleottero", "Erba"], numero: 47, peso: "29,5 kg", altezza: "1,0 m"),
    Pokemon(nomePkmn: "Venonat", categoria: ["Coleottero", "Veleno"], numero: 48, peso: "30,0 kg", altezza: "1,0 m"),
    Pokemon(nomePkmn: "Venomoth", categoria: ["Coleottero", "Veleno"], numero: 49, peso: "12,5 kg", altezza: "1,5 m"),
    Pokemon(nomePkmn: "Diglett", categoria: ["Terra", ""], numero: 50, peso: "0,8 kg", altezza: "0,2 m"),
    Pokemon(nomePkmn: "Dugtrio", categoria: ["Terra", ""], numero: 51, peso: "33,3 kg", altezza: "0,7 m"),
    Pokemon(nomePkmn: "Meowth", categoria: ["Normale", ""], numero: 52, peso: "4,2 kg", altezza: "0,4 m"),
    Pokemon(nomePkmn: "Persian", categoria: ["Normale", ""], numero: 53, peso: "32,0 kg", altezza: "1,0 m"),
    Pokemon(nomePkmn: "Psyduck", categoria: ["Acqua", ""], numero: 54, peso: "19,6 kg", altezza: "0,8 m"),
    Pokemon(nomePkmn: "Golduck", categoria: ["Acqua", ""], numero: 55, peso: "76,6 kg", altezza: "1,7 m"),
    Pokemon(nomePkmn: "Mankey", categoria: ["Lotta", ""], numero: 56, peso: "28,0 kg", altezza: "0,5 m"),
    Pokemon(nomePkmn: "Primeape", categoria: ["Lotta", ""], numero: 57, peso: "32,0 kg", altezza: "1,0 m"),
    Pokemon(nomePkmn: "Growlithe", categoria: ["Fuoco", ""], numero: 58, peso: "19,0 kg", altezza: "0,7 m"),
    Pokemon(nomePkmn: "Arcanine", categoria: ["Fuoco", ""], numero: 59, peso: "155,0 kg", altezza: "1,9 m"),
    Pokemon(nomePkmn: "Poliwag", categoria: ["Acqua", ""], numero: 60, peso: "12,4 kg", altezza: "0,6 m"),
    Pokemon(nomePkmn: "Poliwhirl", categoria: ["Acqua", ""], numero: 61, peso: "20,0 kg", altezza: "1,0 m"),
    Pokemon(nomePkmn: "Poliwrath", categoria: ["Acqua", "Lotta"], numero: 62, peso: "54,0 kg", altezza: "1,3 m"),
    Pokemon(nomePkmn: "Abra", categoria: ["Psico", ""], numero: 63, peso: "19,5 kg", altezza: "0,9 m"),
    Pokemon(nomePkmn: "Kadabra", categoria: ["Psico", ""], numero: 64, peso: "56,5 kg", altezza: "1,3 m"),
    Pokemon(nomePkmn: "Alakazam", categoria: ["Psico", ""], numero: 65, peso: "48,0 kg", altezza: "1,5 m"),
    Pokemon(nomePkmn: "Machop", categoria: ["Lotta", ""], numero: 66, peso: "0,8 kg", altezza: "0,8 m"),
    Pokemon(nomePkmn: "Machoke", categoria: ["Lotta", ""], numero: 67, peso: "70,5 kg", altezza: "1,5 m"),
    Pokemon(nomePkmn: "Machamp", categoria: ["Lotta", ""], numero: 68, peso: "130,0 kg", altezza: "1,6 m"),
    Pokemon(nomePkmn: "Bellsprout", categoria: ["Erba", "Veleno"], numero: 69, peso: "4,0 kg", altezza: "0,7 m"),
    Pokemon(nomePkmn: "Weepinbell", categoria: ["Erba", "Veleno"], numero: 70, peso: "6,4 kg", altezza: "1,0 m"),
    Pokemon(nomePkmn: "Victreebel", categoria: ["Erba", "Veleno"], numero: 71, peso: "15,5 kg", altezza: "1,7 m"),
    Pokemon(nomePkmn: "Tentacool", categoria: ["Acqua", "Veleno"], numero: 72, peso: "45,5 kg", altezza: "0,9 m"),
    Pokemon(nomePkmn: "Tentacruel", categoria: ["Acqua", "Veleno"], numero: 73, peso: "55,0 kg", altezza: "1,6 m"),
    Pokemon(nomePkmn: "Geodude", categoria: ["Roccia", "Terra"], numero: 74, peso: "20,0 kg", altezza: "0,4 m"),
    Pokemon(nomePkmn: "Graveler", categoria: ["Roccia", "Terra"], numero: 75, peso: "105,0 kg", altezza: "1,0 m"),
    Pokemon(nomePkmn: "Golem", categoria: ["Roccia","Terra"], numero: 76, peso: "300,0 kg", altezza: "1,4 m"),
    Pokemon(nomePkmn: "Ponyta", categoria: ["Fuoco", ""], numero: 77, peso: "30,0 kg", altezza: "1,0 m"),
    Pokemon(nomePkmn: "Rapidash", categoria: ["Fuoco", ""], numero: 78, peso: "95,0 kg", altezza: "1,7 m"),
    Pokemon(nomePkmn: "Slowpoke", categoria: ["Acqua", "Psico"], numero: 79, peso: "36,0 kg", altezza: "1,2 m"),
    Pokemon(nomePkmn: "Slowbro", categoria: ["Acqua", "Psico"], numero: 80, peso: "78,5 kg", altezza: "1,6 m"),
    Pokemon(nomePkmn: "Magnemite", categoria: ["Elettro", "Acciaio"], numero: 81, peso: "6,0 kg", altezza: "0,3 m"),
    Pokemon(nomePkmn: "Magneton", categoria: ["Elettro", "Acciaio"], numero: 82, peso: "60,0 kg", altezza: "1,0 m"),
    Pokemon(nomePkmn: "Farfetch'd", categoria: ["Normale", "Volante"], numero: 83, peso: "15,0 kg", altezza: "0,8 m"),
    Pokemon(nomePkmn: "Doduo", categoria: ["Normale", "Volante"], numero: 84, peso: "39,2 kg", altezza: "1,4 m"),
    Pokemon(nomePkmn: "Dodrio", categoria: ["Normale", "Volante"], numero: 85, peso: "85,2 kg", altezza: "1,8 m"),
    Pokemon(nomePkmn: "Seel", categoria: ["Acqua", ""], numero: 86, peso: "90,0 kg", altezza: "1,1 m"),
    Pokemon(nomePkmn: "Dewgong", categoria: ["Acqua", "Ghiaccio"], numero: 87, peso: "120,0 kg", altezza: "1,7 m"),
    Pokemon(nomePkmn: "Grimer", categoria: ["Veleno", ""], numero: 88, peso: "30,0 kg", altezza: "0,9 m"),
    Pokemon(nomePkmn: "Muk", categoria: ["Veleno", ""], numero: 89, peso: "30,0 kg", altezza: "1,2 m"),
    Pokemon(nomePkmn: "Shellder", categoria: ["Acqua", ""], numero: 90, peso: "4,0 kg", altezza: "0,3 m"),
    Pokemon(nomePkmn: "Cloyster", categoria: ["Acqua", "Ghiaccio"], numero: 91, peso: "132,5 kg", altezza: "1,7 m"),
    Pokemon(nomePkmn: "Gastly", categoria: ["Spettro", "Volante"], numero: 92, peso: "0,1 kg", altezza: "1,3 m"),
    Pokemon(nomePkmn: "Hunter", categoria: ["Spettro", "Volante"], numero: 93, peso: "0,1 kg", altezza: "1,6 m"),
    Pokemon(nomePkmn: "Gengar", categoria: ["Spettro", "Volante"], numero: 94, peso: "40,5 kg", altezza: "1,5 m"),
    Pokemon(nomePkmn: "Onix", categoria: ["Roccia", "Terra"], numero: 95, peso: "210,0 kg", altezza: "8,8 m"),
    Pokemon(nomePkmn: "Drowzee", categoria: ["Psico", ""], numero: 96, peso: "32,4 kg", altezza: "1,0 m"),
    Pokemon(nomePkmn: "Hypno", categoria: ["Psico", ""], numero: 97, peso: "75,6 kg", altezza: "1,6 m"),
    Pokemon(nomePkmn: "Krabby", categoria: ["Acqua", ""], numero: 98, peso: "6,5 kg", altezza: "0,4 m"),
    Pokemon(nomePkmn: "Kingler", categoria: ["Acqua", ""], numero: 99, peso: "60,0 kg", altezza: "1,3 m"),
    Pokemon(nomePkmn: "Voltorb", categoria: ["Elettro", ""], numero: 100, peso: "10,4 kg", altezza: "0,5 m"),
    Pokemon(nomePkmn: "Electrode", categoria: ["Elettro", ""], numero: 101, peso: "66,6 kg", altezza: "1,2 m"),
    Pokemon(nomePkmn: "Exeggcute", categoria: ["Erba", "Psico"], numero: 102, peso: "2,5 kg", altezza: "0,4 m"),
    Pokemon(nomePkmn: "Exeggutor", categoria: ["Erba", "Psico"], numero: 103, peso: "120,0 kg", altezza: "2,0 m"),
    Pokemon(nomePkmn: "Cubone", categoria: ["Terra", ""], numero: 104, peso: "6,5 kg", altezza: "0,4 m"),
    Pokemon(nomePkmn: "Marowak", categoria: ["Terra", ""], numero: 105, peso: "45,0 kg", altezza: "1,0 m"),
    Pokemon(nomePkmn: "Hitmonlee", categoria: ["Lotta", ""], numero: 106, peso: "49,8 kg", altezza: "1,5 m"),
    Pokemon(nomePkmn: "Hitmonchan", categoria: ["Lotta", ""], numero: 107, peso: "50,2 kg", altezza: "1,4 m"),
    Pokemon(nomePkmn: "Lickitung", categoria: ["Normale", ""], numero: 108, peso: "65,5 kg", altezza: "1,2 m"),
    Pokemon(nomePkmn: "Koffing", categoria: ["Veleno", ""], numero: 109, peso: "1,0 kg", altezza: "0,6 m"),
    Pokemon(nomePkmn: "Weezing", categoria: ["Veleno", ""], numero: 110, peso: "9,5 kg", altezza: "1,2 m"),
    Pokemon(nomePkmn: "Rhyhorn", categoria: ["Terra", "Roccia"], numero: 111, peso: "115,0 kg", altezza: "1,0 m"),
    Pokemon(nomePkmn: "Rhydon", categoria: ["Terra", "Roccia"], numero: 112, peso: "120,0 kg", altezza: "1,9 m"),
    Pokemon(nomePkmn: "Chansey", categoria: ["Normale", ""], numero: 113, peso: "34,6 kg", altezza: "1,1 m"),
    Pokemon(nomePkmn: "Tangela", categoria: ["Erba", ""], numero: 114, peso: "35,0 kg", altezza: "1,0 m"),
    Pokemon(nomePkmn: "Kangaskhan", categoria: ["Normale", ""], numero: 115, peso: "80,0 kg", altezza: "2,2 m"),
    Pokemon(nomePkmn: "Horsea", categoria: ["Acqua", ""], numero: 116, peso: "8,0 kg", altezza: "0,4 m"),
    Pokemon(nomePkmn: "Seadra", categoria: ["Acqua", ""], numero: 117, peso: "25,0 kg", altezza: "1,2 m"),
    Pokemon(nomePkmn: "Goldeen", categoria: ["Acqua", ""], numero: 118, peso: "15,0 kg", altezza: "0,6 m"),
    Pokemon(nomePkmn: "Seaking", categoria: ["Acqua", ""], numero: 119, peso: "39,0 kg", altezza: "1,3 m"),
    Pokemon(nomePkmn: "Staryu", categoria: ["Acqua", ""], numero: 120, peso: "34,5 kg", altezza: "0,8 m"),
    Pokemon(nomePkmn: "Starmie", categoria: ["Acqua", "Psico"], numero: 121, peso: "80,0 kg", altezza: "1,1 m"),
    Pokemon(nomePkmn: "Mr.Mime", categoria: ["Psico", "Folletto"], numero: 122, peso: "54,5 kg", altezza: "1,3 m"),
    Pokemon(nomePkmn: "Schyter", categoria: ["Coleottero", "Volante"], numero: 123, peso: "56,0 kg", altezza: "1,5 m"),
    Pokemon(nomePkmn: "Jinx", categoria: ["Ghiaccio", "Psico"], numero: 124, peso: "40,6 kg", altezza: "1,4 m"),
    Pokemon(nomePkmn: "Electabuzz", categoria: ["Elettro", ""], numero: 125, peso: "30,0 kg", altezza: "1,1 m"),
    Pokemon(nomePkmn: "Magmar", categoria: ["Fuoco", ""], numero: 126, peso: "44,5 kg", altezza: "1,3 m"),
    Pokemon(nomePkmn: "Pinsir", categoria: ["Coleottero", ""], numero: 127, peso: "55,0 kg", altezza: "1,5 m"),
    Pokemon(nomePkmn: "Tauros", categoria: ["Normale", ""], numero: 128, peso: "88,4 kg", altezza: "1,4 m"),
    Pokemon(nomePkmn: "Magikarp", categoria: ["Acqua", ""], numero: 129, peso: "10,0 kg", altezza: "0,9 m"),
    Pokemon(nomePkmn: "Gyarados", categoria: ["Acqua", "Volante"], numero: 130, peso: "235,0 kg", altezza: "6,5 m"),
    Pokemon(nomePkmn: "Lapras", categoria: ["Acqua", "Ghiaccio"], numero: 131, peso: "220,0 kg", altezza: "2,5 m"),
    Pokemon(nomePkmn: "Ditto", categoria: ["Normale", ""], numero: 132, peso: "4,0 kg", altezza: "0,3 m"),
    Pokemon(nomePkmn: "Eevee", categoria: ["Normale", ""], numero: 133, peso: "6,5 kg", altezza: "0,3 m"),
    Pokemon(nomePkmn: "Vaporeon", categoria: ["Acqua", ""], numero: 134, peso: "29,0 kg", altezza: "1,0 m"),
    Pokemon(nomePkmn: "Jolteon", categoria: ["Elettro", ""], numero: 135, peso: "6,9 kg", altezza: "0,7 m"),
    Pokemon(nomePkmn: "Flareon", categoria: ["Fuoco", ""], numero: 136, peso: "25,0 kg", altezza: "0,9 m"),
    Pokemon(nomePkmn: "Porygon", categoria: ["Normale", ""], numero: 137, peso: "36,5 kg", altezza: "0,8 m"),
    Pokemon(nomePkmn: "Omanyte", categoria: ["Roccia", "Acqua"], numero: 138, peso: "7,5 kg", altezza: "0,4 m"),
    Pokemon(nomePkmn: "Omastar", categoria: ["Roccia", "Acqua"], numero: 139, peso: "35,0 kg", altezza: "1,0 m"),
    Pokemon(nomePkmn: "Kabuto", categoria: ["Roccia", "Acqua"], numero: 140, peso: "11,5 kg", altezza: "0,5 m"),
    Pokemon(nomePkmn: "Kabutops", categoria: ["Roccia", "Acqua"], numero: 141, peso: "40,5 kg", altezza: "1,3 m"),
    Pokemon(nomePkmn: "Aerodactyl", categoria: ["Roccia", "Volante"], numero: 142, peso: "59 kg", altezza: "1,8 m"),
    Pokemon(nomePkmn: "Snorlax", categoria: ["Normale", ""], numero: 143, peso: "460,0 kg", altezza: "2,1 m"),
    Pokemon(nomePkmn: "Articuno", categoria: ["Ghiaccio", "Volante"], numero: 144, peso: "55,4 kg", altezza: "1,7 m"),
    Pokemon(nomePkmn: "Zapdos", categoria: ["Elettro", "Volante"], numero: 145, peso: "52,6 kg", altezza: "1,6 m"),
    Pokemon(nomePkmn: "Moltres", categoria: ["Fuoco", "Volante"], numero: 146, peso: "60,0 kg", altezza: "2,0 m"),
    Pokemon(nomePkmn: "Dratini", categoria: ["Drago", ""], numero: 147, peso: "3,3 kg", altezza: "1,8 m"),
    Pokemon(nomePkmn: "Dragonair", categoria: ["Drago", ""], numero: 148, peso: "16,5 kg", altezza: "4,0 m"),
    Pokemon(nomePkmn: "Dragonite", categoria: ["Drago", "Volante"], numero: 149, peso: "210,0 kg", altezza: "2,2 m"),
    Pokemon(nomePkmn: "Mewtwo", categoria: ["Psico", ""], numero: 150, peso: "122,0 kg", altezza: "2,0 m"),
    Pokemon(nomePkmn: "Mew", categoria: ["Psico", ""], numero: 151, peso: "4,0 kg", altezza: "0,4 m")
]
